/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nRfmxyMRsY2
 */
import { Recipe } from "@/types";
import GalleryItem from "./galleryItem";

type GalleryProps = {
  recipes: Recipe[];
};

export function Gallery({ recipes }: GalleryProps) {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 w-full max-w-6xl px-4">
      {recipes.map((recipe) => (
        <GalleryItem key={recipe.name} {...recipe} />
      ))}
    </div>
  );
}
