/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/2lwPb4xBj4m
 */
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";

export function NewRecipeForm() {
  return (
    <div className="mx-auto max-w-md space-y-6">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">New Fujifilm Film Recipe</h1>
        <p className="text-gray-500 dark:text-gray-400">
          Enter the details of your new film recipe
        </p>
      </div>
      <div className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="name">Recipe Name</Label>
          <Input
            id="name"
            placeholder="Enter recipe name"
            required
            name="name"
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="description">Description</Label>
          <Textarea
            className="min-h-[100px]"
            id="description"
            placeholder="Enter description"
            required
            name="description"
          />
        </div>
        <div className="grid grid-cols-3 gap-4">
          <div className="space-y-2">
            <Label htmlFor="iso">ISO</Label>
            <Input id="iso" placeholder="Enter ISO" required name="iso" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="aperture">Aperture</Label>
            <Input
              id="aperture"
              placeholder="Enter aperture"
              required
              name="aperture"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="shutterSpeed">Shutter Speed</Label>
            <Input
              id="shutterSpeed"
              placeholder="Enter shutter speed"
              required
              name="shutterSpeed"
            />
          </div>
        </div>
        <div className="grid w-full max-w-sm items-center gap-1.5">
          <Label htmlFor="image">Image</Label>
          <Input
            id="image"
            required
            type="file"
            accept="image/*"
            name="image"
          />
        </div>
        <Button className="w-full" type="submit">
          Create Recipe
        </Button>
      </div>
    </div>
  );
}
